### ISSUE TITLE
org/jboss/aerogear/cordova/push/Message.java Need to be modified

### ISSUE THREAD

**Issue by DrArmaggedon** [aerogear/aerogear-titanium-push#1]
There is a problem in Message.java that prevent the NotificationMessageHandler to retreive the stored messages. Please check the https://github.com/aerogear/aerogear-cordova-push/pull/107 and update Message.java accordingly.

**Comment by camilamacedo86** [comment]
The issue opened for more than 2 years. Closing since shows outdated.
